### ISSUE TITLE
Support java 6

### ISSUE THREAD

**Issue by takacsot** [nebula-plugins/gradle-extra-configurations-plugin#28]
When using java 6 environment I got error message of "Unsupported major.minor version 51.0"

If there is not specific reason against it would be great to support java 6 too.

**Comment by rspieldenner** [comment]
Feel free to fork and release internally to your org. Java 7 is already end
of life so these are more likely to roll on to Java 8 or 9.

**Comment by DanielThomas** [comment]
IIRC, Gradle also plans on moving to Java 7 compatibility for Gradle itself, so Java 6 support would be a stop gap at best.
