### ISSUE TITLE
provided not working for fileTree(...)

### ISSUE THREAD

**Issue by Favorlock** [nebula-plugins/gradle-extra-configurations-plugin#29]
I have `provided fileTree(dir: 'lib', include: '*.jar')` as a dependency to include libraries that aren't available via repository management, however, all of the file dependencies appear to shade when using Shadow.

Any chance you can look into a fix for this?

** edit **
I managed to achieve the results I was looking for by having the following:
```java
idea {
    module {
        scopes.PROVIDED.plus += [configurations.shadow]
    }
}

tasks.withType(AbstractCompile) {
    classpath += configurations.shadow
}

dependencies {
    shadow fileTree(dir: 'lib', include: '*.jar')
}
```
The provided configuration does not work on files however, so would still like to see support for that if possible.

**Comment by rspieldenner** [comment]
provided does not work with gradle 3.4 and newer. So will not fix.
