### ISSUE TITLE
OptionalBasePlugin.configureMavenPlugin is not compatible with Gradle 8.0

### ISSUE THREAD

**Issue by ljacomet** [nebula-plugins/gradle-extra-configurations-plugin#53]
Gradle 8.0 finalizes the [removal of the legacy `maven` plugin](https://github.com/gradle/gradle/pull/22807/commits/c66a3542e5a35738b5c4a1c69b96615f8a7600ca). The `MavenPlugin` class remained available in Gradle 7.0 mostly for plugins compatibility.

And the `OptionalBasePlugin` indeed still has a reference to it in its `configureMavenPlugin` method.

This reference should be made indirect and only ever used in Gradle < 8.0

**Comment by rpalcolea** [comment]
Hey @ljacomet ! thanks for bringing this up. we removed this in https://github.com/nebula-plugins/gradle-extra-configurations-plugin/commit/8572372a62dfdeee1341307f88a0dad1c9203252
